# Generated by Django 4.2.11 on 2026-06-03 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('event_type', models.CharField(blank=True, default='', max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Webhook Log',
                'verbose_name_plural': 'Webhook Logs',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('mpamba', 'TNM Mpamba'), ('airtel_money', 'Airtel Money'), ('paychangu', 'PayChangu')], default='paychangu', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('payment_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=2000.0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_fee_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('distributed_to_wallets', models.BooleanField(default=False, help_text='Whether money has been distributed to wallets')),
                ('distributed_at', models.DateTimeField(blank=True, help_text='When money was sent to wallets', null=True)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, help_text='Platform fee taken from this payment', max_digits=10)),
                ('restaurant_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount going to restaurant', max_digits=10)),
                ('driver_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount going to driver', max_digits=10)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount refunded', max_digits=10)),
                ('refund_reason', models.TextField(blank=True, default='', help_text='Reason for refund')),
                ('refunded_at', models.DateTimeField(blank=True, help_text='When refund was processed', null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When payment was completed', null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
