# Generated by Django 4.2.11 on 2026-06-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pending_restaurant_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount held for restaurant, pending their confirmation', max_digits=10),
        ),
    ]
