# Generated by Django 6.0.5 on 2026-05-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_webhooklog_alter_payment_options_payment_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('mpamba', 'TNM Mpamba'), ('airtel_money', 'Airtel Money')], default='mpamba', max_length=20),
        ),
    ]
