# Generated by Django 6.0.5 on 2026-05-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='distributed_at',
            field=models.DateTimeField(blank=True, help_text='When money was sent to wallets', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='distributed_to_wallets',
            field=models.BooleanField(default=False, help_text='Whether money has been distributed to wallets'),
        ),
        migrations.AddField(
            model_name='payment',
            name='driver_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount going to driver', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform fee taken from this payment', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='restaurant_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount going to restaurant', max_digits=10),
        ),
    ]
