# Generated by Django 6.0.5 on 2026-05-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_delivery_fee_payment_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='When payment was completed', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for refund'),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount refunded', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, help_text='When refund was processed', null=True),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='event_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
