# Generated by Django 6.0.5 on 2026-05-27 21:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_menuitem_options_alter_restaurant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='base_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=1000.0, help_text='Base delivery fee', max_digits=6),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='fee_per_km',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Fee per kilometer', max_digits=6),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='free_delivery_radius',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Radius in km where delivery is free', max_digits=6),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='max_delivery_radius',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Maximum delivery radius in km', max_digits=6),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tier_1_fee',
            field=models.DecimalField(decimal_places=2, default=1000.0, help_text='Fee for tier 1 (0-2km)', max_digits=6),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tier_2_fee',
            field=models.DecimalField(decimal_places=2, default=2000.0, help_text='Fee for tier 2 (2-5km)', max_digits=6),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tier_3_fee',
            field=models.DecimalField(decimal_places=2, default=3000.0, help_text='Fee for tier 3 (5-8km)', max_digits=6),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tier_4_fee',
            field=models.DecimalField(decimal_places=2, default=4000.0, help_text='Fee for tier 4 (8-12km)', max_digits=6),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tier_5_fee',
            field=models.DecimalField(decimal_places=2, default=5000.0, help_text='Fee for tier 5 (12-15km)', max_digits=6),
        ),
        migrations.CreateModel(
            name='RestaurantWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='restaurants.restaurantwallet')),
            ],
        ),
    ]
