# Generated by Django 6.0.5 on 2026-05-29 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverlocationhistory',
            name='delivery_assignment',
        ),
        migrations.RemoveField(
            model_name='driverlocationhistory',
            name='driver',
        ),
        migrations.AlterModelOptions(
            name='deliveryassignment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='deliveryassignment',
            old_name='assigned_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='deliveryassignment',
            name='actual_time_minutes',
        ),
        migrations.RemoveField(
            model_name='deliveryassignment',
            name='arrived_at',
        ),
        migrations.RemoveField(
            model_name='deliveryassignment',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='deliveryassignment',
            name='customer_feedback',
        ),
        migrations.RemoveField(
            model_name='deliveryassignment',
            name='customer_rating',
        ),
        migrations.RemoveField(
            model_name='deliveryassignment',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='deliveryassignment',
            name='dropoff_latitude',
        ),
        migrations.RemoveField(
            model_name='deliveryassignment',
            name='dropoff_longitude',
        ),
        migrations.RemoveField(
            model_name='deliveryassignment',
            name='estimated_time_minutes',
        ),
        migrations.RemoveField(
            model_name='deliveryassignment',
            name='pickup_latitude',
        ),
        migrations.RemoveField(
            model_name='deliveryassignment',
            name='pickup_longitude',
        ),
        migrations.RemoveField(
            model_name='deliveryassignment',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='deliveryassignment',
            name='tip_amount',
        ),
        migrations.RemoveField(
            model_name='deliveryassignment',
            name='total_earning',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='id_card_photo',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='license_photo',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='total_ratings',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='verification_documents',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='verification_notes',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='drivers.driverprofile'),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='status',
            field=models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('busy', 'Busy - On Delivery')], default='offline', max_length=20),
        ),
        migrations.DeleteModel(
            name='DriverEarning',
        ),
        migrations.DeleteModel(
            name='DriverLocationHistory',
        ),
    ]
