# Generated by Django 6.0.3 on 2026-03-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('restaurant', 'Restaurant Owner'), ('driver', 'Delivery Driver'), ('admin', 'Administrator')], default='customer', max_length=20),
        ),
    ]
