# Generated by Django 6.0.5 on 2026-05-28 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_current_latitude_user_current_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_longitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_available',
        ),
    ]
