# Generated by Django 6.0.5 on 2026-05-21 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='When driver marked as delivered', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When customer confirmed delivery', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_confirmed_by_customer',
            field=models.BooleanField(default=False, help_text="Customer clicked 'Confirm Delivery'"),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance in kilometers from restaurant to customer', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When driver accepted the order', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_arrived_at',
            field=models.DateTimeField(blank=True, help_text='When driver arrived at restaurant', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_assigned_at',
            field=models.DateTimeField(blank=True, help_text='When driver was assigned', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_id',
            field=models.IntegerField(blank=True, help_text='ID of assigned driver', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_name',
            field=models.CharField(blank=True, default='', help_text="Driver's name for display", max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_payment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid to driver', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_picked_up_at',
            field=models.DateTimeField(blank=True, help_text='When driver picked up food', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='escrow_released_at',
            field=models.DateTimeField(blank=True, help_text='When money left escrow', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='money_distributed',
            field=models.BooleanField(default=False, help_text='Money has been sent to wallets'),
        ),
        migrations.AddField(
            model_name='order',
            name='money_distributed_at',
            field=models.DateTimeField(blank=True, help_text='When money was sent to wallets', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='When customer completed payment', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mpamba', 'TNM Mpamba'), ('airtel_money', 'Airtel Money'), ('card', 'Card'), ('cash', 'Cash on Delivery')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='PayChangu transaction reference', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('escrow', 'In Escrow'), ('distributed', 'Distributed to Wallets'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform fee (10%)', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_payment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid to restaurant', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('driver_assigned', 'Driver Assigned'), ('driver_arrived', 'Driver Arrived at Restaurant'), ('preparing', 'Preparing'), ('ready', 'Ready for Pickup'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('holding', 'Holding'), ('released', 'Released'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], default='holding', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('platform_fee_held', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('restaurant_amount_held', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('driver_amount_held', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('held_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='orders.order')),
            ],
            options={
                'verbose_name': 'Escrow',
                'verbose_name_plural': 'Escrows',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='Unique reference like TXN-20241223-001', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('customer_payment', 'Customer Payment'), ('platform_fee', 'Platform Fee'), ('restaurant_earning', 'Restaurant Earning'), ('driver_earning', 'Driver Earning'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund'), ('bonus', 'Bonus')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('reference', models.CharField(blank=True, help_text='External reference (PayChangu, etc)', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='orders.order')),
                ('user', models.ForeignKey(blank=True, help_text='Null for platform transactions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('restaurant', 'Restaurant Owner'), ('driver', 'Driver'), ('platform', 'Platform'), ('admin', 'Admin')], default='customer', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Current wallet balance', max_digits=12)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, help_text='Money waiting to be available', max_digits=12)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, help_text='Lifetime earnings', max_digits=12)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0, help_text='Money withdrawn', max_digits=12)),
                ('currency', models.CharField(default='MWK', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Null for platform wallet', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('phone_number', models.CharField(max_length=20)),
                ('provider', models.CharField(choices=[('mpamba', 'TNM Mpamba'), ('airtel_money', 'Airtel Money')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='PayChangu withdrawal reference', max_length=200, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': 'Withdrawal Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
